language: "python"
python: "3.6"
cache: "pip"
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "Yc3S9/aLTNd/8vq25/x0FqUiHVIPnoDKjyb89I5Ae1X2Hhgeq3R1szY/H4nRprYA2hNusDNxIeuGdQskVTEbvBBV6PeV/D2D5wjLVianCPIIbspII/kkkvbNfpd6GVHpXz5FUVGu4eTC1GV70CDI+tRPRDA/qzbZUmMgIFYGA/3YhZSIgHVve2su77MMlUiSF40dbijcHoKFfCWlKXWII+HpwcJDgkN5wVCtIRBASBxtXdUVj/0P/zHLI1oRMGsQ2yzvaaIj88AG2+44PozNbDl3xECctcpfa9KqbPRbCqLfjDEVKuhfFNsddHMYkiLHIp48KsfSl1ixZVa4p7pEMvK+EHkscOrmeNqHOIJY2SKZxwJJpfiXjJZqirn21qztRGTFF/yo8IZUZvJndptCxpOYvZ3eE6v0i+v3duf49ivPN7yhzJmzj1haOQHjMpRWIt4kz5zYba8TqIodFkU+JVUsgxuLvT++eISFeFC0AE6BQirBO3UXAX+Zw/WqLbW4MLS9hB/0DeFpInEbMkqUPXkSLtYtluGiw40jk7uGsWVrCWNH5RYD5kB66jDie48dp2mCUe3KH3DaMqboTsZ4M8RS74sq5A+mkflL86ZbQx5+gkffy+AjPExKpxYzt9PX77BfNsevFBKiQhMrwzFWQV7E8MX4qNgPBGTqDiHNcV0="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "honzajavorek/prazeni.honzajavorek.cz"
