language: "python"
python: "3.5"
cache: "pip"
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "YR1czDDtbI75DUq2yo+hgQjbWXEHaUtVrr3IJcduGT+fyK4r6xoTS041e4I7sBQf5//FC9K0oodD4diBQDe6Uar/aaJx6Gf1IELwFoH5rYV8K2+khuet2reWs4VExxkOqUL3pP/oVyK2iMfY5VVKUc3ukiC2qbfV7x22RD+5BChm+SPrw5OTj08vrGZ3mXEDWIaAWNNxL/mNYdV73DQkROm0oNTi0O5EFw2ly5uT3OYBrkA7zqkD5B3y83XBrL+xveIdh0ElZeyF4ZIqOfUt4bYS+V3p31TE8UA8fEmln8JO4Dz3hnUAcJ/oI96Zen/HVkl8dv1I911yQkxkQkPYt9O1SjV8jiSARm/0/k858qLO17+qV69SezuxFO/Wefku01UAKVl/ReKwRDWbikD+CZsb5RG7luiAQZi4zLWmQpVaL9uvq0/wgUgGGycypZ7kQQ5hyvWm1mbow2cp6D9GsSj5WkEceyuZHsVcHBiquuqwWshQhSBERwdRPUqu/3sNJ9oqBjH9B16DyXbrdtIMEC2VKushDKf7q4GNZzBcFY7qMi+Y0IECreOUDAYf+XYUbGhndS3vBK2w2kh/2iYXvcibAfcRw13kyrmExYyHtvOBKWZ/BfJQ+ox8/xCvdL3HP0b+pOb+WNDjH4FUY3NLcHiLsp8tUk36bAy+JVIszYA="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "honzajavorek/prazeni.honzajavorek.cz"
