language: "python"
python: "3.6"
cache: "pip"
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "VXFI4WAIVIhTePZkOVNZAplIbuwkq0GbmSJaoVPB8y+TDNz+4yiEtqpDmc5+ACMYaievLpSPMgNw5YxIQnUbvI6ncxEhiQ2I3CW605EK9eczaYqnQWo1+4snf8bwVasl99t4AK12bY/ihe5N2BPPlAqoPzmZ3qL82L44B+0QeQMIh2zKACKD2dgy5BlD31mq796IV4jmzcJIfW6dvQUEJSp8MXctDtP297d6i/djh+Qs7ZxkeDO0LEou3cII13E648Iqst6DYMeZRCuDEIQe2fdOZZx5LsIl7M/RkYixLaRHr0wi7BO05TmNebuaavxiOMSa1UEGe1kGU1lxstSWqXFVHleeVwjnXKqJhzXN/UwGM9Rfa5WfsS0dcFpHFJCBr1w67J9RZFwTDP96b3HHRCYfh4vYsz3W57tVyPIIriX1VBQC/X6vxhjpG6pamKhGXnk8Yz0vjT4KY8YqoQ3HbW/N/vMGsqLHVuBVUC193cBj4f+9apJi54cKWSix3u91avFsOpVLoXhzcqRdxiUEwTgEQ/hWXX9w8VSCPSiOYJLv9JI+3ZTUdzAewUYqacgnSp4MNRrtKhIL/cUPRdSdg+T74C2nca1sAA5qG36PNTBBSNVV/AsIOdTYB/+m3LaX7Sm/Vv/Q55Hg/ug4ZUUl5BpyfnPodBAN4JbLEjnbNcY="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "honzajavorek/prazeni.honzajavorek.cz"
